# Generated by Django 5.2.15 on 2026-06-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('item_category', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('GST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
    ]
