# Generated by Django 5.2.15 on 2026-07-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_info',
            name='stock',
            field=models.CharField(default=True),
        ),
    ]
