# Generated by Django 5.2.15 on 2026-07-01 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_info_gst_remove_product_info_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_info',
            old_name='Cost_price',
            new_name='cost_price',
        ),
        migrations.RenameField(
            model_name='product_info',
            old_name='Selling_price',
            new_name='selling_price',
        ),
    ]
