# Generated by Django 5.2.15 on 2026-07-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_info_quantity_product_info_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_info',
            name='user_id',
        ),
    ]
