# Generated by Django 6.0.6 on 2026-07-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_uploadbatch_invalidrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadbatch',
            name='user',
        ),
        migrations.DeleteModel(
            name='InvalidRow',
        ),
        migrations.DeleteModel(
            name='UploadBatch',
        ),
    ]
