# Generated by Django 6.0.6 on 2026-07-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_invaliduploadrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct_info',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=500),
        ),
        migrations.AlterField(
            model_name='historicalproduct_info',
            name='item_category',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='historicalproduct_info',
            name='product_code',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalproduct_info',
            name='product_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalproduct_info',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historicalproduct_info',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=500),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=500),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='item_category',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='product_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='product_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=500),
        ),
    ]
