# Generated by Django 6.0.6 on 2026-07-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_uploadsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_db',
            name='cc_email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='email_db',
            name='subject',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='email_db',
            name='to_email',
            field=models.EmailField(default='sivaprakash622003@gmail.com', max_length=100),
        ),
    ]
